# Hypothesis Testing

In [4492]:
import numpy as np
import pandas as pd
import random
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4493]:
pre_df = pd.read_csv('keystroke.csv')

## Removing outliers

In [4479]:
from scipy import stats

z_scores = stats.zscore(pre_df[['H.period', 'DD.period.t',
       'UD.period.t', 'H.t', 'DD.t.i', 'UD.t.i', 'H.i', 'DD.i.e', 'UD.i.e',
       'H.e', 'DD.e.five', 'UD.e.five', 'H.five', 'DD.five.Shift.r',
       'UD.five.Shift.r', 'H.Shift.r', 'DD.Shift.r.o', 'UD.Shift.r.o', 'H.o',
       'DD.o.a', 'UD.o.a', 'H.a', 'DD.a.n', 'UD.a.n', 'H.n', 'DD.n.l',
       'UD.n.l', 'H.l', 'DD.l.Return', 'UD.l.Return', 'H.Return']],axis=1)

abs_z_scores = np.abs(z_scores)
filtered_entries = (abs_z_scores < 3.5).all(axis=1)
org_df = pre_df[filtered_entries]

org_df = org_df.reset_index()
org_df = org_df.drop('index',axis=1)

In [4494]:
org_df['subject'] = org_df['subject'].apply(lambda x: int(x[2:]))

In [4495]:
org_df

,subject,sessionIndex,rep,H.period,DD.period.t,UD.period.t,H.t,DD.t.i,UD.t.i,H.i,...,H.a,DD.a.n,UD.a.n,H.n,DD.n.l,UD.n.l,H.l,DD.l.Return,UD.l.Return,H.Return
0,2,1,1,0.1491,0.3979,0.2488,0.1069,0.1674,0.0605,0.1169,...,0.1349,0.1484,0.0135,0.0932,0.3515,0.2583,0.1338,0.3509,0.2171,0.0742
1,2,1,2,0.1111,0.3451,0.2340,0.0694,0.1283,0.0589,0.0908,...,0.1412,0.2558,0.1146,0.1146,0.2642,0.1496,0.0839,0.2756,0.1917,0.0747
2,2,1,3,0.1328,0.2072,0.0744,0.0731,0.1291,0.0560,0.0821,...,0.1621,0.2332,0.0711,0.1172,0.2705,0.1533,0.1085,0.2847,0.1762,0.0945
3,2,1,4,0.1291,0.2515,0.1224,0.1059,0.2495,0.1436,0.1040,...,0.1457,0.1629,0.0172,0.0866,0.2341,0.1475,0.0845,0.3232,0.2387,0.0813
4,2,1,5,0.1249,0.2317,0.1068,0.0895,0.1676,0.0781,0.0903,...,0.1312,0.1582,0.0270,0.0884,0.2517,0.1633,0.0903,0.2517,0.1614,0.0818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,57,8,46,0.0884,0.0685,-0.0199,0.1095,0.1290,0.0195,0.0945,...,0.1219,0.1383,0.0164,0.0820,0.1329,0.0509,0.1005,0.2054,0.1049,0.1047
20396,57,8,47,0.0655,0.0630,-0.0025,0.0910,0.1148,0.0238,0.0916,...,0.1008,0.0512,-0.0496,0.1037,0.0868,-0.0169,0.1445,0.2206,0.0761,0.1198
20397,57,8,48,0.0939,0.1189,0.0250,0.1008,0.1122,0.0114,0.0721,...,0.0913,0.1169,0.0256,0.0689,0.1311,0.0622,0.1034,0.2017,0.0983,0.0905
20398,57,8,49,0.0923,0.1294,0.0371,0.0913,0.0990,0.0077,0.0992,...,0.0882,0.0821,-0.0061,0.0576,0.0697,0.0121,0.0979,0.1917,0.0938,0.0931
20399,57,8,50,0.0596,0.1310,0.0714,0.0992,0.1103,0.0111,0.0998,...,0.0969,0.0784,-0.0185,0.0790,0.1133,0.0343,0.0807,0.1993,0.1186,0.1018

## Feature engineering - NOT USED

In [ ]:
'''org_df['H_mean'] = org_df[['H.period', 'H.t', 'H.i', 'H.e',
       'H.five', 'H.Shift.r', 'H.o', 'H.a', 'H.n', 'H.l', 'H.Return']].apply(lambda x: x.mean(),axis=1)

org_df['H_std'] = org_df[['H.period', 'H.t', 'H.i', 'H.e',
       'H.five', 'H.Shift.r', 'H.o', 'H.a', 'H.n', 'H.l', 'H.Return']].apply(lambda x: x.std(),axis=1)

org_df['DD_mean'] = org_df[['DD.period.t', 'DD.t.i', 'DD.i.e',
       'DD.e.five', 'DD.five.Shift.r', 'DD.Shift.r.o', 'DD.o.a', 'DD.a.n',
       'DD.n.l', 'DD.l.Return']].apply(lambda x: x.mean(),axis=1)

org_df['DD_std'] = org_df[['DD.period.t', 'DD.t.i', 'DD.i.e',
       'DD.e.five', 'DD.five.Shift.r', 'DD.Shift.r.o', 'DD.o.a', 'DD.a.n',
       'DD.n.l', 'DD.l.Return']].apply(lambda x: x.std(),axis=1)

org_df['UD_mean'] = org_df[['UD.period.t', 'UD.t.i', 'UD.i.e',
       'UD.e.five', 'UD.five.Shift.r', 'UD.Shift.r.o', 'UD.o.a', 'UD.a.n',
       'UD.n.l', 'UD.l.Return']].apply(lambda x: x.mean(),axis=1)

org_df['UD_std'] = org_df[['UD.period.t', 'UD.t.i', 'UD.i.e',
       'UD.e.five', 'UD.five.Shift.r', 'UD.Shift.r.o', 'UD.o.a', 'UD.a.n',
       'UD.n.l', 'UD.l.Return']].apply(lambda x: x.std(),axis=1)'''

In [4497]:
org_df

,subject,sessionIndex,rep,H.period,DD.period.t,UD.period.t,H.t,DD.t.i,UD.t.i,H.i,...,H.l,DD.l.Return,UD.l.Return,H.Return,H_mean,H_std,DD_mean,DD_std,UD_mean,UD_std
0,2,1,1,0.1491,0.3979,0.2488,0.1069,0.1674,0.0605,0.1169,...,0.1338,0.3509,0.2171,0.0742,0.115782,0.022530,0.54039,0.493923,0.42045,0.492082
1,2,1,2,0.1111,0.3451,0.2340,0.0694,0.1283,0.0589,0.0908,...,0.0839,0.2756,0.1917,0.0747,0.100100,0.029165,0.43400,0.361336,0.33136,0.363031
2,2,1,3,0.1328,0.2072,0.0744,0.0731,0.1291,0.0560,0.0821,...,0.1085,0.2847,0.1762,0.0945,0.111109,0.029826,0.39526,0.298385,0.28249,0.304275
3,2,1,4,0.1291,0.2515,0.1224,0.1059,0.2495,0.1436,0.1040,...,0.0845,0.3232,0.2387,0.0813,0.105400,0.023856,0.46450,0.405723,0.35669,0.410564
4,2,1,5,0.1249,0.2317,0.1068,0.0895,0.1676,0.0781,0.0903,...,0.0903,0.2517,0.1614,0.0818,0.092582,0.025764,0.39389,0.311851,0.30023,0.315000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20395,57,8,46,0.0884,0.0685,-0.0199,0.1095,0.1290,0.0195,0.0945,...,0.1005,0.2054,0.1049,0.1047,0.101364,0.015347,0.14936,0.063340,0.04833,0.068961
20396,57,8,47,0.0655,0.0630,-0.0025,0.0910,0.1148,0.0238,0.0916,...,0.1445,0.2206,0.0761,0.1198,0.100727,0.022356,0.11479,0.066040,0.01597,0.059185
20397,57,8,48,0.0939,0.1189,0.0250,0.1008,0.1122,0.0114,0.0721,...,0.1034,0.2017,0.0983,0.0905,0.083509,0.014318,0.14309,0.054281,0.06028,0.052993
20398,57,8,49,0.0923,0.1294,0.0371,0.0913,0.0990,0.0077,0.0992,...,0.0979,0.1917,0.0938,0.0931,0.086264,0.013601,0.12780,0.069816,0.04222,0.071676
20399,57,8,50,0.0596,0.1310,0.0714,0.0992,0.1103,0.0111,0.0998,...,0.0807,0.1993,0.1186,0.1018,0.093764,0.024285,0.14376,0.064252,0.05080,0.067473

## Dropping highly correlated features - NOT USED

In [4395]:
'''columns = np.array(org_df.columns)
columns = columns[3:]

for i in range(0,len(columns)):
    if 'UD' in columns[i]:
        org_df = org_df.drop(columns[i],axis=1)
'''

In [4452]:
org_df.columns

Index(['subject', 'sessionIndex', 'rep', 'H.period', 'DD.period.t',
       'UD.period.t', 'H.t', 'DD.t.i', 'UD.t.i', 'H.i', 'DD.i.e', 'UD.i.e',
       'H.e', 'DD.e.five', 'UD.e.five', 'H.five', 'DD.five.Shift.r',
       'UD.five.Shift.r', 'H.Shift.r', 'DD.Shift.r.o', 'UD.Shift.r.o', 'H.o',
       'DD.o.a', 'UD.o.a', 'H.a', 'DD.a.n', 'UD.a.n', 'H.n', 'DD.n.l',
       'UD.n.l', 'H.l', 'DD.l.Return', 'UD.l.Return', 'H.Return', 'H_mean',
       'H_std', 'DD_mean', 'DD_std', 'UD_mean', 'UD_std'],
      dtype='object')

## Scaling dataset

In [4498]:
from sklearn.preprocessing import QuantileTransformer

scaler = QuantileTransformer(output_distribution='normal')

org_df[['H.period', 'DD.period.t',
       'UD.period.t', 'H.t', 'DD.t.i', 'UD.t.i', 'H.i', 'DD.i.e', 'UD.i.e',
       'H.e', 'DD.e.five', 'UD.e.five', 'H.five', 'DD.five.Shift.r',
       'UD.five.Shift.r', 'H.Shift.r', 'DD.Shift.r.o', 'UD.Shift.r.o', 'H.o',
       'DD.o.a', 'UD.o.a', 'H.a', 'DD.a.n', 'UD.a.n', 'H.n', 'DD.n.l',
       'UD.n.l', 'H.l', 'DD.l.Return', 'UD.l.Return', 'H.Return', 'H_mean',
       'H_std', 'DD_mean', 'DD_std', 'UD_mean', 'UD_std']] = scaler.fit_transform(org_df[['H.period', 'DD.period.t',
       'UD.period.t', 'H.t', 'DD.t.i', 'UD.t.i', 'H.i', 'DD.i.e', 'UD.i.e',
       'H.e', 'DD.e.five', 'UD.e.five', 'H.five', 'DD.five.Shift.r',
       'UD.five.Shift.r', 'H.Shift.r', 'DD.Shift.r.o', 'UD.Shift.r.o', 'H.o',
       'DD.o.a', 'UD.o.a', 'H.a', 'DD.a.n', 'UD.a.n', 'H.n', 'DD.n.l',
       'UD.n.l', 'H.l', 'DD.l.Return', 'UD.l.Return', 'H.Return', 'H_mean',
       'H_std', 'DD_mean', 'DD_std', 'UD_mean', 'UD_std']])

In [4484]:
org_df

,subject,sessionIndex,rep,H.period,DD.period.t,UD.period.t,H.t,DD.t.i,UD.t.i,H.i,...,H.l,DD.l.Return,UD.l.Return,H.Return,H_mean,H_std,DD_mean,DD_std,UD_mean,UD_std
0,2,1,1,0.385157,0.098674,0.122967,0.421053,0.041478,0.054578,0.346646,...,0.386053,0.060486,0.059415,0.278081,0.538211,0.110478,0.226176,0.191155,0.224597,0.188536
1,2,1,2,0.282232,0.084751,0.119211,0.259275,0.031725,0.054185,0.267073,...,0.237982,0.047192,0.054997,0.280031,0.437961,0.147777,0.171259,0.135979,0.179363,0.134852
2,2,1,3,0.341008,0.048388,0.078713,0.275237,0.031925,0.053474,0.240549,...,0.310979,0.048799,0.052301,0.357254,0.508340,0.151489,0.151262,0.109782,0.154550,0.110409
3,2,1,4,0.330986,0.060069,0.090893,0.416739,0.061954,0.074952,0.307317,...,0.239763,0.055596,0.063172,0.305772,0.471843,0.117930,0.187003,0.154451,0.192224,0.154625
4,2,1,5,0.319610,0.054848,0.086934,0.345988,0.041527,0.058893,0.265549,...,0.256973,0.042972,0.049727,0.307722,0.389899,0.128655,0.150555,0.115386,0.163557,0.114871
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18483,57,8,46,0.220748,0.011813,0.054784,0.432269,0.031900,0.044525,0.278354,...,0.287240,0.034798,0.039900,0.397036,0.446039,0.070100,0.024333,0.011967,0.035658,0.012519
18484,57,8,47,0.158722,0.010363,0.059200,0.352459,0.028358,0.045579,0.269512,...,0.417804,0.037482,0.034891,0.455928,0.441971,0.109500,0.006488,0.013090,0.019228,0.008452
18485,57,8,48,0.235645,0.025103,0.066178,0.394737,0.027710,0.042539,0.210061,...,0.295846,0.034145,0.038752,0.341654,0.331900,0.064315,0.021096,0.008197,0.041726,0.005876
18486,57,8,49,0.231311,0.027872,0.069248,0.353753,0.024418,0.041632,0.292683,...,0.279525,0.032379,0.037969,0.351794,0.349509,0.060283,0.013204,0.014662,0.032556,0.013648
18487,57,8,50,0.142741,0.028294,0.077952,0.387834,0.027236,0.042466,0.294512,...,0.228487,0.033721,0.042283,0.385725,0.397455,0.120344,0.021442,0.012346,0.036912,0.011900

## Taking the log() of all positive values - NOT USED

In [4421]:
'''
import math

columns = np.array(org_df.columns)
columns = columns[-6:]

for col in range(0,len(columns)):
    for row in range(0,18488):
            org_df[columns[col]].iloc[row] = math.log(org_df[columns[col]].iloc[row])*(-1)
'''

'\nimport math\n\ncolumns = np.array(org_df.columns)\ncolumns = columns[-6:]\n\nfor col in range(0,len(columns)):\n    for row in range(0,18488):\n            org_df[columns[col]].iloc[row] = math.log(org_df[columns[col]].iloc[row])*(-1)\n'

## Creating a weighted average per parameter per user

In [4499]:
df_subjects = org_df['subject']
df_multiplier = org_df['rep']
df_divider = org_df[['subject','rep']].groupby('subject').sum()['rep']

In [4500]:
df = org_df[['subject','H.period', 'DD.period.t',
       'UD.period.t', 'H.t', 'DD.t.i', 'UD.t.i', 'H.i', 'DD.i.e', 'UD.i.e',
       'H.e', 'DD.e.five', 'UD.e.five', 'H.five', 'DD.five.Shift.r',
       'UD.five.Shift.r', 'H.Shift.r', 'DD.Shift.r.o', 'UD.Shift.r.o', 'H.o',
       'DD.o.a', 'UD.o.a', 'H.a', 'DD.a.n', 'UD.a.n', 'H.n', 'DD.n.l',
       'UD.n.l', 'H.l', 'DD.l.Return', 'UD.l.Return', 'H.Return', 'H_mean',
       'H_std', 'DD_mean', 'DD_std', 'UD_mean', 'UD_std']].groupby('subject').mean()
df = df.reset_index()

df_no_users = df.drop('subject',axis=1)
org_df = org_df.drop(['sessionIndex','rep'],axis=1)

## Type 1 error testing

### One sample two-sided t-test

In [4518]:
from scipy.stats import ttest_1samp

count = 0

for row in range(0,1000):
    

    user_input = np.array(org_df.iloc[random.randint(0,18488)]).reshape(1,-1)
    x = np.delete(user_input,0,axis=1)
    y = user_input[0][0]

    sample = np.array(x[0])

    profile = np.array(df_no_users.iloc[int(df[df['subject']==y].index.values)])
    
    ttest, pval = ttest_1samp(sample,profile.mean())

    if pval > 0.05:
        count = count+1

print('Accepts true null hypothesis: {}'.format(count/1000))

Accepts true null hypothesis: 0.722

### Independent t-test

In [4516]:
from scipy.stats import ttest_ind

count = 0

for row in range(0,1000):
    

    user_input = np.array(org_df.iloc[random.randint(0,18487)]).reshape(1,-1)
    x = np.delete(user_input,0,axis=1).reshape(1,-1)
    y = user_input[0][0]

    sample = x[0]

    profile = np.array(df_no_users.iloc[int(df[df['subject']==y].index.values)])
    
    ttest, pval = ttest_ind(sample,profile)
    
    if pval > 0.05:
        count = count+1

print('Accepts true null hypothesis: {}'.format(count/1000))

Accepts true null hypothesis: 0.83

### Mann-Whitney test

In [4506]:
from scipy.stats import mannwhitneyu

count = 0

for row in range(0,1000):
    

    user_input = np.array(org_df.iloc[random.randint(0,18487)]).reshape(1,-1)
    x = np.delete(user_input,0,axis=1)
    y = user_input[0][0]

    sample = np.array(x[0])

    profile = np.array(df_no_users.iloc[int(df[df['subject']==y].index.values)])
    
    ttest, pval = mannwhitneyu(sample,profile)

    if pval > 0.05:
        count = count+1

print('Accepts true null hypothesis: {}'.format(count/1000))

Accepts true null hypothesis: 0.726

## Type 2 error testing

### One sample two-sided t-test

In [4505]:
from scipy.stats import ttest_rel

count=0

for row in range(0,1000):
    
    fraud_usr = org_df.iloc[random.randint(0,18488)]
    fraud_sub = fraud_usr['subject']
    fraud_usr_data = fraud_usr.drop('subject')
    sample = np.array(fraud_usr_data)
    
    index = int(df[df['subject']==int(fraud_sub)].index.values)
    
    if len(range(0,index)) > len(range(index,50)):
        attempt = random.randint(0,index-1)
    else:
        attempt = random.randint(index+1,50)
    
    ac_usr = df.iloc[attempt]
    ac_sub = ac_usr['subject']
    ac_usr_data = ac_usr.drop('subject')
    profile = np.array(ac_usr_data)
    
    ttest,pval = ttest_rel(sample,profile)
    
    if pval < 0.05:
        count=count+1

print('Rejects false null hypothesis: {}'.format(count/1000))

Rejects false null hypothesis: 0.585

### Independent t-test

In [4504]:
from scipy.stats import ttest_ind

count=0

for row in range(0,1000):
    
    fraud_usr = org_df.iloc[random.randint(0,18488)]
    fraud_sub = fraud_usr['subject']
    fraud_usr_data = fraud_usr.drop('subject')
    sample = np.array(fraud_usr_data)
    
    index = int(df[df['subject']==int(fraud_sub)].index.values)
    
    if len(range(0,index)) > len(range(index,50)):
        attempt = random.randint(0,index-1)
    else:
        attempt = random.randint(index+1,50)
    
    ac_usr = df.iloc[attempt]
    ac_sub = ac_usr['subject']
    ac_usr_data = ac_usr.drop('subject')
    profile = np.array(ac_usr_data)
    
    ttest,pval = ttest_ind(sample,profile)
    
    if pval < 0.05:
        count=count+1

print('Rejects false null hypothesis: {}'.format(count/1000))

Rejects false null hypothesis: 0.548

### Mann-Whitney test

In [4503]:
from scipy.stats import mannwhitneyu

count=0

for row in range(0,1000):
    
    fraud_usr = org_df.iloc[random.randint(0,18487)]
    fraud_sub = fraud_usr['subject']
    fraud_usr_data = fraud_usr.drop('subject')
    sample = np.array(fraud_usr_data)
    
    index = int(df[df['subject']==int(fraud_sub)].index.values)
    
    if len(range(0,index)) > len(range(index,50)):
        attempt = random.randint(0,index-1)
    else:
        attempt = random.randint(index+1,50)
    
    ac_usr = df.iloc[attempt]
    ac_sub = ac_usr['subject']
    ac_usr_data = ac_usr.drop('subject')
    profile = np.array(ac_usr_data)
    
    ttest,pval = mannwhitneyu(sample,profile)
    
    if pval < 0.05:
        count=count+1

print('Rejects false null hypothesis: {}'.format(count/1000))

Rejects false null hypothesis: 0.615

## Testing for true negatives between user profiles

### T test

In [4502]:
from scipy.stats import ttest_ind

count=0

for row in range(0,49):
    
    sample = df_no_users.iloc[row]
    sample_arr = np.array(sample)
    
    profile = df_no_users.iloc[50]
    profile_arr = np.array(profile)
    
    ttest,pval = ttest_ind(sample_arr,profile_arr)
    
    if pval < 0.05:
        count=count+1
        

print(count/len(range(0,49)))

0.7142857142857143

### Mann-Whitney

In [4501]:
from scipy.stats import mannwhitneyu

count=0

for row in range(0,49):
    
    sample = df_no_users.iloc[row]
    sample_arr = np.array(sample)
    
    profile = df_no_users.iloc[50]
    profile_arr = np.array(profile)
    
    ttest,pval = mannwhitneyu(sample,profile)
    
    if pval < 0.05:
        count=count+1
        

print(count/len(range(0,49)))

0.7755102040816326